// Generates src/ui/glyphPaths.ts from the 8x8 bitmaps in src/ui/mapGlyphs.ts.
// Run with: npm run gen:glyphs
//
// Each bitmap row is scanned for horizontal runs of '#'; every run becomes one
// rectangle subpath (M x y h w v1 h-w z) in an 8x8 viewBox. The bitmaps stay
// the editable source of truth — re-run this whenever you change them.

import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as glyphs from '../src/ui/mapGlyphs.js';

type Bitmap = readonly string[];

function bitmapToPath(rows: Bitmap): string {
  const parts: string[] = [];
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      if (row[x] !== '#') {
        x += 1;
        continue;
      }
      let w = 1;
      while (x + w < row.length && row[x + w] === '#') w += 1;
      parts.push(`M${x} ${y}h${w}v1h-${w}z`);
      x += w;
    }
  });
  return parts.join('');
}

const entries = Object.entries(glyphs).filter(
  // @ts-expect-error tuple type matching
  (entry): entry is [string, Bitmap] =>
    Array.isArray(entry[1]) && entry[1].every((row) => typeof row === 'string')
);

const ids = entries.map(([name]) => name);

const out = [
  '// GENERATED by scripts/generate-glyphs.ts — do not edit by hand.',
  '// Run `npm run gen:glyphs` to regenerate from src/ui/mapGlyphs.ts.',
  '',
  'export type GlyphId =',
  ...ids.map((id, i) => `  | '${id}'${i === ids.length - 1 ? ';' : ''}`),
  '',
  'export const GLYPH_PATHS: Record<GlyphId, string> = {',
  ...entries.map(([name, rows]) => `  ${name}: '${bitmapToPath(rows)}',`),
  '};',
  '',
].join('\n');

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../src/ui/glyphPaths.ts');
writeFileSync(outPath, out);
console.log(`Wrote ${entries.length} glyph paths to ${outPath}`);
